name: test
on:
  pull_request:
    branches: [master]
jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'
      - name: test
        run: go version && go test -race -v ./...
